### ISSUE TITLE
More Trains

### ISSUE THREAD

**Issue by shinenelson** [luser/whatthetrain#12]
Amazing concept. Hats off.

Can we on board all our other products (Firefox OS, Thunderbird, Bugzilla) into the same website? But on different pages. Like have a menu for each on the top. Clicking on a menu item would slide-in the details about that particular train keeping the same layout.

The Firefox OS train could integrate the [FxOS Dashboard](https://marketplace.firefox.com/app/fxos-dashboard) too.

**Comment by luser** [comment]
I'm not particularly concerned about that stuff, especially since Thunderbird versions track Firefox versions. I have no idea how B2G versions track platform versions, so I don't know if that'd be useful.

I'm not interested in tracking Bugzilla versions.

I think the site is pretty good with its existing simplicity, honestly.

**Comment by shinenelson** [comment]
The site is amazing the way it is already. I was just suggesting so that the site could be the ***one-stop place*** to track all of [mozilla](https://mozilla.org/)'s products.

**Comment by luser** [comment]
Thanks, but I don't think I'm going to do this.
